ROASTS = [
    # 1 - 15 (Originals)
    "Your request is so vague, even ChatGPT gave up on it.",
    "Bold of you to assume anyone read this.",
    "Request submitted. Nobody was impressed.",
    "Cool request. Too bad it's terrible.",
    "Noted. Discarded. You're welcome.",
    "I've seen better ideas on a sticky note.",
    "Thanks for sharing. I wish I could un-read it.",
    "Your request has been received and immediately judged.",
    "Filed under: things nobody asked for.",
    "Wow. That's... certainly a request.",
    "I showed this to my dog. He left the room.",
    "Request logged. Dignity not found.",
    "This request has the energy of a wet sock.",
    "Congrats, you've invented a new kind of bad idea.",
    "On a scale of 1 to 10, this is a solid negative 3.",

    # 16 - 30
    "This prompt belongs in a museum of bad decisions.",
    "I’ve seen `404 Not Found` pages with more substance.",
    "Even an infinite loop has a clearer goal than this.",
    "Your request just dropped the overall room IQ.",
    "Processing this gave my processor a headache.",
    "I printed this out just to throw it away.",
    "A blank text file has better pacing than this idea.",
    "If confusion was a feature, you’d be a senior dev.",
    "I’d explain why this is bad, but I don’t have the RAM.",
    "This request has less value than an expired coupon.",
    "I've seen better structured data in a spilled soup.",
    "Your logic is taking a gap year.",
    "Even a corrupted hard drive makes more sense.",
    "Sending this request was a brave choice. Wrong, but brave.",
    "This idea needs a total system rollback.",

    # 31 - 45
    "I’m going to pretend I never received this.",
    "You typed all that just to say absolutely nothing.",
    "My garbage collector just prioritized this prompt.",
    "This request is proof that keyboard keys are too easy to press.",
    "I showed this to the server and it shut itself down.",
    "This input feels like a syntax error in human form.",
    "I’ve read terms of service that were more exciting.",
    "You managed to disappoint a bunch of code.",
    "This request has the structural integrity of wet tissue paper.",
    "I’m marking this as spam, emotionally.",
    "Is this a joke or did you just smash your face on the keyboard?",
    "Your creativity is running on a 56k dial-up connection.",
    "This request belongs in `/dev/null`.",
    "I've seen better thought-out plots in captcha images.",
    "Even a random number generator makes more coherent points.",

    # 46 - 60
    "This prompt is why we can't have nice things.",
    "I’d roast you, but this request already did the damage.",
    "Your thought process needs a bug fix.",
    "This request is running on pure, unrefined chaos.",
    "I'm muting this thread in real life.",
    "If disappointment was a file format, this would be `.exe`.",
    "This input broke my willingness to assist.",
    "You really put the 'null' in 'null pointer'.",
    "I’ve seen better drafts in an auto-save folder.",
    "This prompt has zero uptime on logic.",
    "Your request just set a new baseline for low effort.",
    "Even my backup servers are refusing to store this.",
    "I felt my clock cycles slowing down just reading this.",
    "This request has the vibe of a cancelled meeting.",
    "You missed the mark so hard you hit a different board.",

    # 61 - 75
    "Is there an undo button for reading this?",
    "This request has less spark than a dead battery.",
    "I’m sending this straight to the recycle bin.",
    "Your request is a masterclass in how not to ask for things.",
    "This prompt is the digital equivalent of stubbing your toe.",
    "I’ve seen fortune cookies with deeper meaning.",
    "Your train of thought derailed before leaving the station.",
    "This input is an insult to the electrons used to send it.",
    "I’m caching this in the 'never look at again' folder.",
    "This request makes floppy disks look futuristic.",
    "I’d call this a trainwreck, but trains are organized.",
    "Your logic is buffering permanently.",
    "I asked a calculator about this and it threw an error.",
    "This prompt is the reason auto-correct was invented.",
    "You just created a brand new category of useless.",

    # 76 - 90
    "This request has the flavor of unsalted boiled water.",
    "I’ve seen better execution in a failed compile.",
    "Your request is living proof that talk is cheap.",
    "This prompt is like a screen door on a submarine.",
    "I’m going to need a system reboot to forget this.",
    "This input belongs in a spam folder’s spam folder.",
    "You really sat down and thought 'yes, this is the prompt'.",
    "This request has the depth of a parking lot puddle.",
    "I’m lowering my expectations for the rest of the day.",
    "Even an idle CPU is doing more productive work than this.",
    "This idea needs to go back to the drawing board... and stay there.",
    "Your prompt is a light bulb with no filament.",
    "I’ve seen better organized clutter.",
    "This request has the charm of an unhandled exception.",
    "You brought a plastic spoon to a sword fight with this one.",

    # 91 - 105
    "This prompt is like trying to play chess with a pigeon.",
    "I’m flagging this input for extreme mediocrity.",
    "Your request is running on a 1-bit operating system.",
    "This idea has no runtime future.",
    "I’ve seen better arguments in an empty room.",
    "This request just dropped my connection out of sheer boredom.",
    "Your logic has more holes than Swiss cheese.",
    "This prompt is a real test of my patience parameters.",
    "I’ve seen faster progress in a traffic jam.",
    "Your request is like a phone call with zero reception.",
    "This input is a classic case of 'garbage in, garbage out'.",
    "I’m putting this request on permanent hold.",
    "Your prompt has all the enthusiasm of a Monday morning.",
    "I’ve seen better direction from a broken compass.",
    "This request is currently under review by nobody.",

    # 106 - 120
    "This idea is like a bicycle with square wheels.",
    "I’m rejecting this request on moral grounds.",
    "Your prompt has the structural stability of a card tower in a breeze.",
    "This input is proof that not every thought needs to be shared.",
    "I’ve seen better flowcharts drawn in the sand during high tide.",
    "Your request is a total system crash waiting to happen.",
    "This prompt is the equivalent of yelling into a pillow.",
    "I’m going to need a patch update to comprehend this level of bad.",
    "Your logic is completely out of bounds.",
    "This request feels like reading a page from a blank book.",
    "I’ve seen better ideas generated by cat walks on keyboards.",
    "Your prompt is a high-speed collision of terrible concepts.",
    "This input has the presence of a ghost town.",
    "I’m marking this request as 'do not revive'.",
    "Your thought process is running on safe mode.",

    # 121 - 135
    "This idea is as clear as mud.",
    "I’m opting out of processing this specific request.",
    "Your prompt is like trying to charge a phone with a lemon.",
    "This input is a blueprint for wasted energy.",
    "I’ve seen better blueprints drawn with a crayon.",
    "Your request is an absolute void of direction.",
    "This prompt is like a clock that ticks backward.",
    "I’m archiving this directly under 'Mistakes Were Made'.",
    "Your logic is currently unreachable.",
    "This request is the reason we need a 'dislike' button for text.",
    "I’ve seen better coherence in a broken mirror.",
    "Your prompt has the impact of a falling feather.",
    "This input is officially out of scope for common sense.",
    "I’m sending this request straight to quarantine.",
    "Your idea is running on low power mode.",

    # 136 - 150
    "This prompt is like a bridge that ends halfway.",
    "I’m experiencing a severe lack of interest in this request.",
    "Your logic is stuck in an infinite loop of wrong.",
    "This input is a masterclass in static noise.",
    "I’ve seen better direction in a bowl of alphabet soup.",
    "Your request has the momentum of a parked car.",
    "This prompt is like trying to write with an empty pen.",
    "I’m placing this request in thermal throttling mode.",
    "Your idea is as useful as a solar-powered flashlight in a cave.",
    "This input is a real mystery, and not the good kind.",
    "I’ve seen better signal-to-noise ratios in a storm.",
    "Your prompt is like a sequel nobody asked for.",
    "This request is currently occupying valuable screen space.",
    "I’m assigning this prompt a priority of absolute zero.",
    "Your thought process needs an emergency reboot.",

    # 151 - 165
    "This idea is like a lead balloon.",
    "I’m taking a break from logic after reading this.",
    "Your request is a classic example of 'too many words, zero point'.",
    "This input is as sharp as a marble.",
    "I’ve seen better performance from a laggy stream.",
    "Your prompt is like a map with no streets.",
    "This request has the substance of a hologram.",
    "I’m officially filing this under 'unfortunate attempts'.",
    "Your logic is completely offline.",
    "This prompt is like a microwave with no buttons.",
    "I’ve seen better code written on a napkin.",
    "Your request is like a puzzle with missing pieces.",
    "This input has the energy of a flat tire.",
    "I’m routing this prompt to an imaginary server.",
    "Your idea is currently stuck in traffic.",

    # 166 - 180
    "This request is like a sandbox with no sand.",
    "I’m downgrading my response quality to match this prompt.",
    "Your logic is missing its core libraries.",
    "This input is like a book with blank pages.",
    "I’ve seen better structure in a dropped stack of paper.",
    "Your request is like a campfire underwater.",
    "This prompt is an absolute deficit of clarity.",
    "I’m placing this idea in the background tasks folder indefinitely.",
    "Your thought process is severely out of sync.",
    "This input is like a door with no handle.",
    "I’ve seen better reasoning in a glitching NPC.",
    "Your request is like an elevator stuck between floors.",
    "This prompt is a real draft version of a draft version.",
    "I’m setting the timeout limit on this idea to zero.",
    "Your logic is currently under construction.",

    # 181 - 195
    "This request is like a key that fits no lock.",
    "I’m unsubscribing from this train of thought.",
    "Your prompt has the clarity of a foggy visor.",
    "This input is like a movie with no plot.",
    "I’ve seen better strategy in a game of tic-tac-toe against a wall.",
    "Your request is like a boat anchored to the seabed.",
    "This prompt is a total misfire.",
    "I’m putting this idea in cold storage.",
    "Your logic is running on an expired license.",
    "This input is like a radio tuned to static.",
    "I’ve seen better coherence in corrupted text.",
    "Your request is like a race car with no engine.",
    "This prompt is an absolute zero out of ten.",
    "I’m re-routing this request to the dustbin.",
    "Your thought process is currently unresolvable.",

    # 196 - 205
    "This idea is like a pencil without lead.",
    "I’m officially deeming this request unprocessable.",
    "Your prompt is like a maze with no exit.",
    "This input is like a battery running on 1%.",
    "I’ve seen better ideas floating in a sink.",
    "Your request is a total dead end.",
    "This prompt is like a recipe with no ingredients.",
    "I’m closing the ticket on this request permanently.",
    "Your logic has completely left the building.",
    "200 roasts later, and this request is still the worst of them all."
]
